function net = train_cnn_model(epochs)
    load('/content/datastores.mat');
    load('/content/cnn_layers.mat');
    options = trainingOptions('sgdm', ...
        'InitialLearnRate',0.01, ...
        'MaxEpochs',epochs, ...
        'MiniBatchSize',32, ...
        'ValidationData',imdsVal, ...
        'Plots','none', ...
        'Verbose',true, ...
        'ExecutionEnvironment','gpu');
    tic;
    net = trainNetwork(imdsTrainAug, layers, options);
    fprintf('✅ Training time: %.1f min\n', toc/60);
    save('/content/trained_cnn.mat', 'net');
end
